"""create employees table

Revision ID: 4eb2347deec1
Revises: 
Create Date: 2026-09-30 16:40:13.096508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb2347deec1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('employee_username', sa.String(length=50), nullable=False),
    sa.Column('employee_email', sa.String(length=255), nullable=False),
    sa.Column('employee_role', sa.Enum('EMPLOYEE', 'ADMINISTRATOR', name='employeerole', native_enum=False), nullable=False),
    sa.Column('employee_status', sa.Enum('ACTIVE', 'LOCKED', name='employeestatus', native_enum=False), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unique_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id', 'employee_username', name='uq_employees_company_username')
    )
    op.create_index(op.f('ix_employees_unique_id'), 'employees', ['unique_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_unique_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
