"""unique account per customer

Revision ID: 73b4d5ccf011
Revises: 8a8a88ce71f5
Create Date: 2026-09-27 14:57:33.494078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b4d5ccf011'
down_revision: Union[str, None] = '8a8a88ce71f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'accounts', ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='unique')
    # ### end Alembic commands ###
